//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRSTest {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.Display_TE35 display_TE35;
        
        public Gadgeteer.Modules.Seeed.CellularRadio cellularRadio;
        
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
            this.cellularRadio = new GTM.Seeed.CellularRadio(4) { DebugPrintEnabled = true };
            this.display_TE35 = new GTM.GHIElectronics.Display_TE35(14, 13, 12, 10);
            this.button = new GTM.GHIElectronics.Button(11);
        }


    }
}
